site_name: FPLstat
site_description: Python package for loading and transforming data from the Fantasy Premier League API
site_url: https://james-leslie.github.io/fpl-stat/
repo_url: https://github.com/James-Leslie/fpl-stat
repo_name: James-Leslie/fpl-stat

theme: readthedocs

nav:
    - Home: index.md
    - Installation: install.md
    - Examples:
        - Getting started: examples/0_quickstart.ipynb

plugins:
    - mkdocs-jupyter:
        include: ["examples/*.ipynb"]
        execute: true